services:
  nginx:
    image: nginx:latest
    ports:
      - "8889:80"  # Nginx 对外暴露的端口
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - java-app-1
      - java-app-2
    restart: always

  java-app-1:
    environment:
      APP_NAME: app-1
    image: my-openjdk-app:1.0
    ports:
      - "8081:8080"
    restart: always

  java-app-2:
    environment:
      APP_NAME: app-2
    image: my-openjdk-app:1.0
    ports:
      - "8082:8080"
    restart: always