services:
  nginx:
    image: nginx:latest
    ports:
      - "8889:80"  # Nginx 对外暴露的端口
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - java-app-1
      - java-app-2
    restart: always

  java-app-1:
    environment:
      APP_NAME: app-1
      # 配置 Redis 的连接信息
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    image: my-openjdk-app:1.0
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - redis

  java-app-2:
    environment:
      APP_NAME: app-2
      # 配置 Redis 的连接信息
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    image: my-openjdk-app:1.0
    ports:
      - "8082:8080"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"  # Redis 对外暴露的端口
    restart: always
